- type: replace
  path: /releases/-
  value:
    name: grootfs
    version: latest
- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: dstate-counter
    release: grootfs
    properties:
      dstate-counter:
        interval: 60
