- type: replace
  path: /releases/-
  value:
    name: grootfs
    version: latest

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: grootfs
    release: grootfs
    properties:
      grootfs:
        log_level: debug
        driver: overlay-xfs
        remote_layer_tls:
          cert: ((grootfs_remote_layer_tls.certificate))
          key: ((grootfs_remote_layer_tls.private_key))
          ca_cert: ((grootfs_remote_layer_tls.ca))

- type: replace
  path: /variables/-
  value:
    name: grootfs_remote_layer_tls
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: cell.service.cf.internal
      extended_key_usage:
      - client_auth
      - server_auth
      alternative_names: ["*.cell.service.cf.internal"]

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/image_plugin?
  value: /var/vcap/packages/grootfs/bin/grootfs
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/image_plugin_extra_args?
  value: ["--config", "/var/vcap/jobs/grootfs/config/grootfs_config.yml"]
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/privileged_image_plugin?
  value: /var/vcap/packages/grootfs/bin/grootfs
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/privileged_image_plugin_extra_args?
  value: ["--config", "/var/vcap/jobs/grootfs/config/privileged_grootfs_config.yml"]
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/persistent_image_list
  value: [/var/vcap/packages/cflinuxfs2/rootfs.tar]
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/preloaded_rootfses
  value: ["cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar"]
