---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-release-develop
  - name: grootfs-git-repo

outputs:
  - name: bumped-release-git

run:
  path: grootfs-release-develop/ci/scripts/bump-grootfs-release.sh
