---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-release-version
  - name: grootfs-release-develop

outputs:
  - name: bosh-release

run:
  path: grootfs-release-develop/ci/scripts/create-grootfs-release.sh
