---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: version
  - name: release
  - name: grootfs-release-develop

outputs:
  - name: bosh-release

params:
  NAME: "grootfs"

run:
  path: grootfs-release-develop/ci/scripts/create-bosh-release.sh
  user: root
