---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-release-develop

outputs:
  - name: manifests

params:
  CF_API_URL: api.grootfs-performance.cf-app.com
  CF_PASSWORD:
  CF_USERNAME:

run:
  path: grootfs-release-develop/ci/scripts/enable-docker-feature-flag.sh
  user: root
