---
image_resource:
  type: docker-image
  source:
      repository: cfgarden/garden-ci-ubuntu
      tag: '0.4.0'

platform: linux

inputs:
  - name: garden-runc-release
  - name: grootfs-release-develop

params:
  LOG_LEVEL: debug
  EXTERNAL_IMAGE_PLUGIN_PROVIDED: "true"
  GARDEN_ADDRESS:

run:
  path: grootfs-release-develop/ci/scripts/gats.sh
  user: root
