---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

platform: linux

inputs:
  - name: garden-runc-release-1.5.0
  - name: grootfs-release-develop

params:
  LOG_LEVEL: debug
  EXTERNAL_IMAGE_PLUGIN_PROVIDED: "true"
  GARDEN_ADDRESS:

run:
  path: grootfs-release-develop/ci/scripts/gats.sh
  user: root
