---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-ci-secrets
  - name: grootfs-release-develop
  - name: git-cf-deployment

outputs:
  - name: manifests

params:
  CF_PASSWORD:
  CF_SYSTEM_DOMAIN: grootfs-performance.cf-app.com
  CF_ETCD_CERTS:
  CF_CC_CERTS:
  CF_CONSUL_CERTS:
  CF_DIEGO_CERTS:
  CF_LOGGREGATOR_CERTS:

run:
  path: grootfs-release-develop/ci/scripts/generate-cf-manifest.sh
  user: root
