---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-ci-secrets
  - name: grootfs-release-develop
  - name: git-cf-deployment
  - name: diego-release-git

outputs:
  - name: manifests

params:
  CF_SYSTEM_DOMAIN:
  CF_SECRETS:
  CF_UAA_CERTS:
  CF_PASSWORD:
  CF_ETCD_CERTS:
  CF_CC_CERTS:
  CF_CONSUL_CERTS:
  CF_DIEGO_CERTS:
  CF_LOGGREGATOR_CERTS:
  DATADOG_API_KEY:
  DATADOG_METRIC_PREFIX:
  IAAS:

run:
  path: grootfs-release-develop/ci/scripts/generate-cf-manifest.sh
  user: root
