---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

platform: linux

inputs:
  - name: grootfs-release-develop

params:
  CF_PASSWORD:

outputs:
  - name: integration-config

run:
  path: grootfs-release-develop/ci/scripts/generate-cats-config-json.sh
  user: root
