---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-ci-secrets
  - name: grootfs-release-develop

outputs:
  - name: manifests

params:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD:
  GITHUB_CLIENT_ID:
  GITHUB_CLIENT_SECRET:

run:
  path: grootfs-release-develop/ci/scripts/generate-concourse-manifest.sh
  user: root
