---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
  - name: grootfs-release-develop

params:
  DATADOG_API_KEY:
  ENV:

run:
  path: grootfs-release-develop/ci/scripts/publish-vizzini-execution.sh
