---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-release-develop

params:
  BOSH_TARGET:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CERTIFICATES:
  BOSH_DEPLOYMENT: cf
  JOB_NAME:

run:
  path: grootfs-release-develop/ci/scripts/recreate-job.sh
  user: root
