---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

platform: linux

inputs:
  - name: grootfs-ci-secrets
  - name: grootfs-release-develop
  - name: manifests

params:
  BOSH_MANIFEST:
  BOSH_TARGET:
  BOSH_USER:
  BOSH_PASSWORD:

run:
  path: grootfs-release-develop/ci/scripts/run-cats.sh
  user: root
