---
image_resource:
  type: docker-image
  source:
      repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-release-develop
  - name: grootfs-release-version
  - name: grootfs-ci-secrets

outputs:
  - name: final-release
  - name: release

params:
  PRIVATE_YML:

run:
  path: grootfs-release-develop/ci/scripts/ship-it.sh
  user: root
