---
name: grootfs

# replace with bosh status --uuid
director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: grootfs
    version: latest

jobs:
  - name: grootfs
    instances: 1
    templates:
      - name: grootfs
        release: grootfs
    resource_pool: grootfs
    networks:
      - name: grootfs
    properties:
      grootfs:
        driver: overlay-xfs
        store_size_bytes: 1073741824

networks:
  - name: grootfs
    subnets:
      - range: 10.244.16.4/30
        reserved: [10.244.16.5]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.8/30
        reserved: [10.244.16.9]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.12/30
        reserved: [10.244.16.13]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.16/30
        reserved: [10.244.16.17]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.20/30
        reserved: [10.244.16.21]
        static: []
        cloud_properties:
          name: random

resource_pools:
  # not much point in having more than one resource pool, since it's all
  # in one VM with the same hardware anyway
  - name: grootfs
    network: grootfs
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: grootfs

compilation:
  workers: 3
  network: grootfs
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
