#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app code.cloudfoundry.org/idmapper/...

} > /tmp/packages

echo "code.cloudfoundry.org/grootfs" >> /tmp/packages

cat /tmp/packages | xargs gosub sync
