---
groups:
- name: grootfs
  jobs:
  - grootfs
  - bump-grootfs-release
  - create-grootfs-release
  - deploy-grootfs-bench
  - performance-tests
  - reset-release-lock
- name: grootfs-bench
  jobs:
  - grootfs-bench
  - bump-grootfs-bench-release
  - create-grootfs-bench-release
  - deploy-grootfs-bench
- name: grootfs-garden
  jobs:
  - deploy-garden-grootfs
  - gats
- name: tools
  jobs:
  - build-ci-image
- name: ship-it
  jobs:
  - create-github-release
  - ship-grootfs-release
  - bump-major-grootfs-release
  - bump-minor-grootfs-release
  - bump-master-in-develop

resources:
- name: release-lock
  type: pool
  source:
    uri: git@github.com:cloudfoundry/grootfs-ci-locks.git
    branch: master
    pool: release-lock
    private_key: {{gnome-private-key}}

- name: garden-runc-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/garden-runc-release
    branch: develop
    ignore_paths:
    - ci

- name: grootfs-git-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs.git
    branch: master
    private_key: {{gnome-private-key}}
    ignore_paths:
    - ci/tasks/

- name: grootfs-release-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-release.git
    branch: develop
    private_key: {{gnome-private-key}}

- name: grootfs-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-release.git
    branch: master
    private_key: {{gnome-private-key}}

- name: grootfs-release-version
  type: semver
  source:
    bucket: grootfs-ci-meta
    key: grootfs/bosh-release-version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: eu-west-1
    initial_version: 0.1.0-rc.1
    driver: s3

- name: grootfs-ci-secrets
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-ci-secrets.git
    branch: master
    private_key: {{gnome-private-key}}

- name: grootfs-release-tarball
  type: s3
  source:
    bucket: grootfs-bosh-releases
    regexp: releases/grootfs-(.*).tgz
    region_name: eu-west-1
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: grootfs-bench-release-tarball
  type: s3
  source:
    bucket: grootfs-bench-releases
    regexp: releases/grootfs-bench-(.*).tgz
    region_name: eu-west-1
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: grootfs-bench-git-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-bench.git
    branch: master
    private_key: {{gnome-private-key}}
    ignore_paths:
    - ci/grootfs-bench-tests.yml

- name: grootfs-bench-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-bench-release.git
    branch: master
    private_key: {{gnome-private-key}}
    ignore_paths:
    - ci/tasks/

- name: grootfs-bench-release-version
  type: semver
  source:
    bucket: grootfs-ci-meta
    key: grootfs/bosh-bench-release-version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: eu-west-1
    initial_version: 0.1.0-rc.1
    driver: s3

- name: performance-time-trigger
  type: time
  source:
    interval: 30m

- name: grootfs-bench-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: grootfs-bench
    ignore_ssl: true

- name: garden-grootfs-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: garden-grootfs
    ignore_ssl: true

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: {{aws-stemcell-name}}

- name: slack-alert
  type: slack-notification-docker
  source:
    url: {{slack-alert-url}}

- name: grootfs-tracker
  type: tracker
  source:
    tracker_url: https://www.pivotaltracker.com
    project_id: "1661239"
    token: {{garden-tracker-token}}

- name: grootfs-standalone-gh-release
  type: github-release
  source:
    user: cloudfoundry
    repository: grootfs
    access_token: {{github-access-token}}
    drafts: true

- name: grootfs-gh-release
  type: github-release
  source:
    user: cloudfoundry
    repository: grootfs-release
    access_token: {{github-access-token}}
    drafts: true

- name: golang-ci-image
  type: docker-image
  source:
    repository: cloudfoundry/golang-ci

- name: grootfs-ci-image
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
- name: reset-release-lock
  serial: true
  plan:
  - get: release-lock
  - put: release-lock
    params:
      release: release-lock

- name: grootfs
  public: true
  plan:
  - aggregate:
    - get: grootfs-git-repo
      trigger: true
  - do:
    - aggregate:
      - task: groot-tests
        privileged: true
        file: grootfs-git-repo/ci/tasks/groot-tests.yml
      - task: root-tests
        privileged: true
        file: grootfs-git-repo/ci/tasks/root-tests.yml
      - task: go-vet
        file: grootfs-git-repo/ci/tasks/go-vet.yml
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: System Failure. Explosion Imminent. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: bump-grootfs-release
  serial: true
  plan:
    - do:
      - put: release-lock
        params:
          acquire: true
      - aggregate:
        - get: grootfs-release-develop
        - get: grootfs-git-repo
          trigger: true
          passed:
          - grootfs
      - task: bump-grootfs-release
        file: grootfs-release-develop/ci/tasks/bump-grootfs-release.yml
      - put: grootfs-release-develop
        params:
          repository: bumped-release-git
      on_failure:
        put: slack-alert
        params:
          username: Thanos
          icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
          channel: "#grootfs"
          text: "<!subteam^S1U0HSJ9E|grootfsteam>: What the BOSH? You can bump it yourself. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
      ensure:
        put: release-lock
        params:
          release: release-lock

- name: create-grootfs-release
  serial: true
  plan:
  - aggregate:
    - get: grootfs-release-version
      params:
        pre: rc
    - get: grootfs-release-develop
      trigger: true
    - get: grootfs-git-repo
      passed:
      - bump-grootfs-release
  - put: grootfs-release-version
    params:
      file: grootfs-release-version/number
  - do:
    - task: create-grootfs-release
      file: grootfs-release-develop/ci/tasks/create-grootfs-release.yml
    - put: grootfs-release-tarball
      params:
        from: bosh-release/grootfs-([^/]*).tgz
        to: releases/
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: What the BOSH? You can deploy it yourself. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: deploy-garden-grootfs
  serial_groups: [grootfs-garden-deployment]
  plan:
  - do:
    - aggregate:
      - get: aws-stemcell
      - get: grootfs-ci-secrets
      - get: grootfs-release-develop
      - get: garden-runc-release
        trigger: true
      - get: grootfs-release-tarball
        trigger: true
        passed:
        - create-grootfs-release
    - task: create-garden-runc-release
      file: grootfs-release-develop/ci/tasks/create-garden-runc-release.yml
    - put: garden-grootfs-deployment
      params:
        manifest: grootfs-ci-secrets/deployments/garden-grootfs/aws.yml
        releases:
        - bosh-release/garden-runc.tgz
        - grootfs-release-tarball/*.tgz
        stemcells:
        - aws-stemcell/*.tgz
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: System Failure. Explosion Imminent. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: gats
  serial_groups: [grootfs-garden-deployment]
  plan:
    - aggregate:
      - get: grootfs-release-develop
        trigger: true
        passed: [deploy-garden-grootfs]
      - get: garden-runc-release
        passed: [deploy-garden-grootfs]
    - task: gats
      file: grootfs-release-develop/ci/tasks/gats.yml
      params:
        GARDEN_ADDRESS: 10.0.16.7:7777

- name: bump-grootfs-bench-release
  serial: true
  plan:
    - aggregate:
      - get: grootfs-bench-release
      - get: grootfs-bench-git-repo
        trigger: true
        passed:
        - grootfs-bench
    - do:
      - task: bump-grootfs-bench-release
        file: grootfs-bench-release/ci/tasks/bump-grootfs-bench-release.yml
      - put: grootfs-bench-release
        params:
          repository: bumped-release-git
      on_failure:
        put: slack-alert
        params:
          username: Thanos
          icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
          channel: "#grootfs"
          text: "<!subteam^S1U0HSJ9E|grootfsteam>: It's not the end of the world, it's just the end of this pipeline. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: create-grootfs-bench-release
  serial: true
  plan:
    - aggregate:
      - get: aws-stemcell
      - get: grootfs-ci-secrets
      - get: grootfs-bench-release
        trigger: true
      - get: grootfs-bench-git-repo
        passed:
        - bump-grootfs-bench-release
      - get: grootfs-bench-release-version
        params:
          pre: rc
    - do:
      - put: grootfs-bench-release-version
        params:
          file: grootfs-bench-release-version/number
      - task: create-release
        file: grootfs-bench-release/ci/tasks/create-grootfs-bench-release.yml
      - put: grootfs-bench-release-tarball
        params:
          from: bosh-release/grootfs-bench-([^/]*).tgz
          to: releases/
      on_failure:
        put: slack-alert
        params:
          username: Thanos
          icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
          channel: "#grootfs"
          text: "<!subteam^S1U0HSJ9E|grootfsteam>: You know what, fix it. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: deploy-grootfs-bench
  serial_groups:
  - bosh-deployment
  plan:
  - do:
    - aggregate:
      - get: grootfs-release-develop
        trigger: true
        passed:
        - create-grootfs-release
      - get: grootfs-release-tarball
        trigger: true
        passed:
        - create-grootfs-release
      - get: grootfs-bench-release
        passed:
        - create-grootfs-bench-release
      - get: grootfs-bench-release-tarball
        trigger: true
        passed:
        - create-grootfs-bench-release
      - get: aws-stemcell
        trigger: true
      - get: grootfs-ci-secrets
    - put: grootfs-bench-deployment
      params:
        manifest: grootfs-ci-secrets/deployments/grootfs-bench/aws.yml
        releases:
        - grootfs-release-tarball/*.tgz
        - grootfs-bench-release-tarball/*.tgz
        stemcells:
        - aws-stemcell/*.tgz
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: What the BOSH? You can deploy it yourself. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: performance-tests
  serial_groups:
  - bosh-deployment
  plan:
  public: true
  plan:
  - do:
    - aggregate:
      - get: grootfs-release-develop
        trigger: true
        passed:
        - deploy-grootfs-bench
      - get: grootfs-bench-release
        trigger: true
        passed:
        - deploy-grootfs-bench
      - get: performance-time-trigger
        trigger: true
      - get: grootfs-ci-secrets
    - task: benchmark
      privileged: true
      file: grootfs-bench-release/ci/tasks/performance-tests.yml
      params:
        BOSH_TARGET: {{bosh-target}}
        BOSH_USER: {{bosh-username}}
        BOSH_PASSWORD: {{bosh-password}}
        BOSH_MANIFEST: grootfs-ci-secrets/deployments/grootfs-bench/aws.yml
        DATADOG_API_KEY: {{datadog-api-key}}
        DATADOG_APPLICATION_KEY: {{datadog-application-key}}
    - put: grootfs-tracker
      params:
        repos:
        - grootfs-release-develop/src/code.cloudfoundry.org/grootfs
        - grootfs-release-develop
        - grootfs-bench-release/src/code.cloudfoundry.org/grootfs-bench
        - grootfs-bench-release
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: You don't need metrics for a thing that doesn't even work! http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: bump-major-grootfs-release
  serial: true
  plan:
  - get: grootfs-release-version
    params: { bump: major, pre: rc }
  - put: grootfs-release-version
    resource: grootfs-release-version
    params: { file: grootfs-release-version/number }

- name: bump-minor-grootfs-release
  serial: true
  plan:
  - get: grootfs-release-version
    params: { bump: minor, pre: rc }
  - put: grootfs-release-version
    resource: grootfs-release-version
    params: { file: grootfs-release-version/number }

- name: ship-grootfs-release
  serial: true
  plan:
  - do:
    - put: release-lock
      params:
        acquire: true
    - aggregate:
      - get: grootfs-ci-secrets
      - get: grootfs-release-develop
        passed:
        - deploy-grootfs-bench
      - get: grootfs-release-master
      - get: grootfs-release-version
        params:
          bump: final
    - task: ship-it
      file: grootfs-release-develop/ci/tasks/ship-it.yml
    - aggregate:
      - put: grootfs-release-master
        params:
          repository: release/master
          tag: grootfs-release-version/number
          tag_prefix: v
      - put: grootfs-release-tarball
        params:
          from: final-release/grootfs-([^/]*).tgz
          to: releases/
      - put: grootfs-gh-release
        params:
          name: grootfs-release-version/number
          tag: grootfs-release-version/number
          tag_prefix: v
          globs:
          - final-release/grootfs-([^/]*).tgz
      - put: rootfs-release-version-pushed
        resource: grootfs-release-version
        params: { bump: patch, pre: rc }
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: Final bosh release went super wrong. Sorry. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: create-github-release
  plan:
  - do:
    - aggregate:
      - get: grootfs-release-master
        passed:
        - ship-grootfs-release
      - get: grootfs-release-version
        trigger: true
        passed:
        - ship-grootfs-release
        params: { bump: final }
    - task: build-grootfs
      file: grootfs-release-master/src/code.cloudfoundry.org/grootfs/ci/tasks/build-grootfs.yml
    - put: grootfs-ci-image
      params:
        build: grootfs-release-master/src/code.cloudfoundry.org/grootfs
        tag_prefix: v
        tag: grootfs-release-version/number
    - put: grootfs-git-repo
      params:
        tag: grootfs-release-version/number
        tag_prefix: v
        repository: grootfs-release-master/src/code.cloudfoundry.org/grootfs
    - put: grootfs-standalone-gh-release
      params:
        name: grootfs-release-version/number
        tag: grootfs-release-version/number
        tag_prefix: v
        globs:
        - build-grootfs/grootfs.tgz
        - build-grootfs/drax.tgz
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: I don't know how to create github release anyway!  http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: bump-master-in-develop
  serial: true
  plan:
  - do:
    - get: release-lock
      passed:
      - ship-grootfs-release
    - aggregate:
      - get: grootfs-release-develop
      - get: grootfs-release-master
        passed:
        - ship-grootfs-release
        trigger: true
    - put: grootfs-release-develop
      params:
        repository: grootfs-release-master
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: I CAN'T BUMP DEVELOP. http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
    ensure:
      put: release-lock
      params:
        release: release-lock

- name: grootfs-bench
  public: true
  plan:
  - aggregate:
    - get: grootfs-bench-git-repo
      trigger: true
  - task: grootfs-bench-tests
    file: grootfs-bench-git-repo/ci/grootfs-bench-tests.yml
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: I've destroyed your build (groot tests are dead). Come and get me!  http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"

- name: build-ci-image
  plan:
  - aggregate:
    - get: grootfs-git-repo
    - get: golang-ci-image
      trigger: true
  - put: grootfs-ci-image
    params:
      build: grootfs-git-repo

resource_types:
- name: slack-notification-docker
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
