---
groups:
- name: grootfs
  jobs:
  - grootfs
  - bump-grootfs-release
  - create-github-release
  - performance-tests
- name: grootfs-release
  jobs:
  - bump-grootfs-release
  - deploy-grootfs-release
- name: tools
  jobs:
  - build-ci-image
  - grootfs-bench
- name: ship-it
  jobs:
  - ship-grootfs-release
  - bump-major-grootfs-release
  - bump-minor-grootfs-release

resources:
- name: grootfs-git-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs.git
    branch: master
    private_key: {{gnome-private-key}}
    ignore_paths:
    - ci/pipeline.yml

- name: grootfs-release-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-release.git
    branch: develop
    private_key: {{gnome-private-key}}

- name: grootfs-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-release.git
    branch: master
    private_key: {{gnome-private-key}}

- name: grootfs-release-version
  type: semver
  source:
    bucket: grootfs-ci-meta
    key: grootfs/bosh-release-version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: eu-west-1
    initial_version: 0.1.0-rc.1
    driver: s3

- name: grootfs-ci-secrets
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-ci-secrets.git
    branch: master
    private_key: {{gnome-private-key}}

- name: grootfs-release-tarball
  type: s3
  source:
    bucket: grootfs-bosh-releases
    regexp: releases/grootfs-(.*).tgz
    region_name: eu-west-1
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: grootfs-bench-git-repo
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-bench.git
    branch: master
    private_key: {{gnome-private-key}}

- name: grootfs-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: grootfs
    ignore_ssl: true

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: {{aws-stemcell-name}}

- name: slack-alert
  type: slack-notification-docker
  source:
    url: {{slack-alert-url}}

- name: grootfs-tracker
  type: tracker
  source:
    tracker_url: https://www.pivotaltracker.com
    project_id: "1661239"
    token: {{garden-tracker-token}}

- name: grootfs-version
  type: semver
  source:
    bucket: grootfs-ci-meta
    key: grootfs/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: eu-west-1
    initial_version: 0.1.0-dev.1
    driver: s3

- name: grootfs-gh-release
  type: github-release
  source:
    user: cloudfoundry
    repository: grootfs
    access_token: {{github-access-token}}
    drafts: true

- name: golang-ci-image
  type: docker-image
  source:
    repository: cloudfoundry/golang-ci

- name: grootfs-ci-image
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
- name: grootfs
  public: true
  plan:
  - aggregate:
    - get: grootfs-version
      params: { pre: 'dev' }
    - get: grootfs-git-repo
      trigger: true
  - put: grootfs-version
    params: { file: grootfs-version/number }
  - do:
    - aggregate:
      - task: groot-tests
        privileged: true
        file: grootfs-git-repo/ci/tasks/groot-tests.yml
      - task: root-tests
        privileged: true
        file: grootfs-git-repo/ci/tasks/root-tests.yml
      - task: go-vet
        file: grootfs-git-repo/ci/tasks/go-vet.yml
    - put: grootfs-tracker
      params:
        repos:
        - grootfs-git-repo
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: System Failure. Explosion Imminent."

- name: bump-grootfs-release
  serial: true
  plan:
    - aggregate:
      - get: grootfs-release-develop
      - get: grootfs-git-repo
        trigger: true
        passed: [grootfs]
    - do:
      - task: bump-grootfs-release
        file: grootfs-release-develop/ci/tasks/bump-grootfs-release.yml
      - put: grootfs-release-develop
        params:
          repository: bumped-release-git
      on_failure:
        put: slack-alert
        params:
          username: Thanos
          icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
          channel: "#grootfs"
          text: "<!subteam^S1U0HSJ9E|grootfsteam>: What the BOSH? You can bump it yourself."

- name: deploy-grootfs-release
  serial: true
  plan:
  - aggregate:
    - get: aws-stemcell
    - get: grootfs-release-version
      params:
        pre: rc
    - get: grootfs-release-develop
      trigger: true
  - put: grootfs-release-version
    params:
      file: grootfs-release-version/number
  - do:
    - task: create-grootfs-release
      file: grootfs-release-develop/ci/tasks/create-grootfs-release.yml
    - aggregate:
      - put: grootfs-deployment
        params:
          manifest: grootfs-release-develop/manifests/aws.yml
          releases: [bosh-release/*.tgz]
          stemcells: [aws-stemcell/*.tgz]
      - put: grootfs-release-tarball
        params:
          from: bosh-release/grootfs-([^/]*).tgz
          to: releases/
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: What the BOSH? You can deploy it yourself."

- name: bump-major-grootfs-release
  serial: true
  plan:
  - get: grootfs-release-version
    params: { bump: major, pre: rc }
  - put: grootfs-release-version
    resource: grootfs-release-version
    params: { file: grootfs-release-version/number }

- name: bump-minor-grootfs-release
  serial: true
  plan:
  - get: grootfs-release-version
    params: { bump: minor, pre: rc }
  - put: grootfs-release-version
    resource: grootfs-release-version
    params: { file: grootfs-release-version/number }

- name: ship-grootfs-release
  serial: true
  plan:
  - do:
    - aggregate:
      - get: grootfs-ci-secrets
      - get: grootfs-release-develop
        passed: [deploy-grootfs-release]
      - get: grootfs-release-master
      - get: grootfs-release-version
        params:
          bump: final
    - task: ship-it
      file: grootfs-release-develop/ci/tasks/ship-it.yml
    - aggregate:
      - put: grootfs-release-master
        params:
          repository: release/master
          tag: grootfs-release-version/number
          tag_prefix: v
      - put: grootfs-release-tarball
        params:
          from: final-release/grootfs-([^/]*).tgz
          to: releases/
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: Final bosh release went super wrong. Sorry."

- name: performance-tests
  public: true
  plan:
  - aggregate:
    - get: grootfs-git-repo
      trigger: true
      passed: [grootfs]
    - get: grootfs-bench-git-repo
  - task: benchmark
    privileged: true
    file: grootfs-git-repo/ci/tasks/performance-tests.yml
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: You don't need metrics for a thing that doesn't even work! http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
    params:
      DATADOG_API_KEY: {{datadog-api-key}}
      DATADOG_APPLICATION_KEY: {{datadog-application-key}}

- name: create-github-release
  plan:
  - aggregate:
    - get: grootfs-git-repo
      passed: [grootfs]
    - get: grootfs-version
      passed: [grootfs]
      params: { bump: final }
  - task: build-grootfs
    file: grootfs-git-repo/ci/tasks/build-grootfs.yml
  - put: grootfs-ci-image
    params:
      build: grootfs-git-repo
      tag_prefix: v
      tag: grootfs-version/number
  - put: grootfs-git-repo
    params:
      tag: grootfs-version/number
      tag_prefix: v
      repository: build-grootfs
  - put: grootfs-gh-release
    params:
      name: grootfs-version/number
      tag: grootfs-version/number
      tag_prefix: v
      globs:
      - build-grootfs/grootfs.tgz
  - get: grootfs-next-dev-version
    resource: grootfs-version
    params: { bump: minor, pre: dev }
  - put: grootfs-next-dev-version
    resource: grootfs-version
    params: { file: grootfs-next-dev-version/number }


- name: grootfs-bench
  public: true
  plan:
  - aggregate:
    - get: grootfs-bench-git-repo
      trigger: true
  - task: grootfs-bench-tests
    file: grootfs-bench-git-repo/ci/grootfs-bench-tests.yml
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#grootfs"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: I've destroyed your build (groot tests are dead). Come and get me!  http://grootfs.ci.cf-app.com/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
  - put: grootfs-tracker
    params:
      repos:
      - grootfs-bench-git-repo

- name: build-ci-image
  plan:
  - aggregate:
    - get: grootfs-git-repo
    - get: golang-ci-image
      trigger: true
  - put: grootfs-ci-image
    params:
      build: grootfs-git-repo

resource_types:
- name: slack-notification-docker
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
