---
resources:
- name: diego-release-git
  type: git
  source:
    uri: https://github.com/cloudfoundry/diego-release
    branch: master

- name: diegocanaryapp
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/diegocanaryapp.git

- name: git-cf-deployment
  type: git
  source:
    uri: https://github.com/masters-of-cats/cf-deployment
    branch: master

- name: thanos-cf-deployment
  type: bosh-deployment-resource
  source:
    target: {{thanos-bosh-target}}
    client: {{thanos-bosh-username}}
    client_secret: {{thanos-bosh-password}}
    ca_cert: {{thanos-root-ca-cert}}
    deployment: cf

- name: garden-runc-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/diego-release

- name: cflinuxfs2-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-release

- name: datadog-nozzle-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/datadog-firehose-nozzle-release

- name: grootfs-release-develop
  type: git
  source:
    uri: {{grootfs-release-git-repo}}
    branch: develop
    private_key: {{gnome-private-key}}

- name: grootfs-diagnostics-develop
  type: git
  source:
    uri: {{grootfs-diagnostics-release-git-repo}}
    branch: develop
    private_key: {{gnome-private-key}}

- name: grootfs-diagnostics-release-tarball
  type: s3
  source:
    bucket: grootfs-bosh-releases
    regexp: {{diagnostics-s3-release-tarball-regexp}}
    region_name: eu-west-1
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: grootfs-ci-secrets
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-ci-secrets.git
    branch: master
    private_key: {{gnome-private-key}}

- name: grootfs-release-tarball
  type: s3
  source:
    bucket: grootfs-bosh-releases
    regexp: {{s3-release-tarball-regexp}}
    region_name: eu-west-1
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: grootfs-bench-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/grootfs-bench-release.git
    branch: master
    private_key: {{gnome-private-key}}

- name: thanos-bench-time-trigger
  type: time
  source:
    interval: 10m

- name: vizzini-time-trigger
  type: time
  source:
    location: Europe/London
    interval: 15m

- name: vizzini-rootfs-refresher
  type: time
  source:
    interval: 2h

- name: thanos-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{thanos-bosh-stemcell-name}}

- name: datadog-event
  type: datadog-event
  source:
    api_key: {{datadog-api-key}}
    application_key: {{datadog-application-key}}

jobs:
- name: deploy-thanos-cf
  serial_groups: [deploy-thanos-cf]
  plan:
  - aggregate:
    - get: grootfs-diagnostics-release-tarball
      trigger: true
    - get: grootfs-release-tarball
    - get: git-cf-deployment
      trigger: true
    - get: grootfs-release-develop
      trigger: true
      params:
        submodules: none
    - get: grootfs-diagnostics-develop
      params:
        submodules: none
    - get: grootfs-ci-secrets
    - get: thanos-bosh-stemcell
    - get: garden-runc-release
      trigger: true
    - get: cflinuxfs2-release
    - get: diego-release
      trigger: true
    - get: diego-release-git
      params:
        submodules: none
    - get: diegocanaryapp
    - get: datadog-nozzle-release
  - task: generate-cf-manifest
    file: grootfs-release-develop/ci/tasks/generate-thanos-cf-manifest.yml
    params:
      CF_SYSTEM_DOMAIN: grootfs-thanos.cf-app.com
      CF_PASSWORD: {{thanos-cf-password}}
      CF_SECRETS: {{thanos-cf-secrets}}
      CF_UAA_CERTS: {{thanos-cf-uaa-certs}}
      CF_ETCD_CERTS: {{thanos-cf-etcd-certs}}
      CF_CC_CERTS: {{thanos-cf-cc-certs}}
      CF_CONSUL_CERTS: {{thanos-cf-consul-certs}}
      CF_DIEGO_CERTS: {{thanos-cf-diego-certs}}
      CF_LOGGREGATOR_CERTS: {{thanos-cf-loggregator-certs}}
      CF_NETWORKING: {{thanos-cf-networking}}
      DATADOG_API_KEY: {{datadog-api-key}}
      DATADOG_APPLICATION_KEY: {{datadog-application-key}}
      DATADOG_METRIC_PREFIX: "datadog.thanos.nozzle."
  - put: thanos-cf-deployment
    tags: [thanos]
    params:
      manifest: manifests/cf.yml
      releases:
      - diego-release/*.tgz
      - cflinuxfs2-release/*.tgz
      - grootfs-release-tarball/*.tgz
      - grootfs-diagnostics-release-tarball/*.tgz
      - garden-runc-release/*.tgz
      - datadog-nozzle-release/*.tgz
      stemcells:
      - thanos-bosh-stemcell/*.tgz
  - task: enable-docker-feature-flag
    tags: [thanos]
    file: grootfs-release-develop/ci/tasks/enable-docker-feature-flag.yml
    params:
      CF_API_URL: api.grootfs-thanos.cf-app.com
      CF_USERNAME: {{thanos-cf-username}}
      CF_PASSWORD: {{thanos-cf-password}}
  - task: isolate-canaries
    tags: [thanos]
    file: grootfs-release-develop/ci/tasks/isolate-canaries.yml
    params:
      DATADOG_API_KEY: {{datadog-api-key}}
      CF_API_URL: api.grootfs-thanos.cf-app.com
      CF_USERNAME: {{thanos-cf-username}}
      CF_PASSWORD: {{thanos-cf-password}}

- name: thanos-refresh-rootfs
  serial_groups: [vizzini]
  plan:
  - get: vizzini-rootfs-refresher
    trigger: true
  - get: grootfs-release-develop
    params:
      submodules: none
  - task: force-unpack-cflinuxfs2-loop
    tags: [thanos]
    privileged: true
    file: grootfs-release-develop/ci/tasks/force-unpack.yml
    params:
      BOSH_TARGET: {{thanos-bosh-target}}
      BOSH_CLIENT: {{thanos-bosh-username}}
      BOSH_CLIENT_SECRET: {{thanos-bosh-password}}
      BOSH_CERTIFICATES: {{thanos-bosh-certificates}}
      CELL_NAME: diego-cell
      CLEAN: true
  - put: datadog-event
    params:
      title: thanos-rootfs-refresh
      text: The rootfs was refreshed

- name: thanos-vizzini-grootfs
  serial_groups: [vizzini]
  plan:
  - aggregate:
    - get: vizzini-time-trigger
      trigger: true
    - get: diego-release-git
    - get: grootfs-release-develop
      params:
        submodules: none
  - task: publish-datadog-event
    file: grootfs-release-develop/ci/tasks/publish-datadog-event.yml
    params:
      DATADOG_API_KEY: {{datadog-api-key}}
      EVENT_NAME: "vizzini-starting-standard-groot"
      TAG: grootfs
  - task: run-vizzini-grootfs
    tags: [thanos]
    privileged: true
    file: grootfs-release-develop/ci/tasks/vizzini-ginkgo.yml
    params:
      BOSH_TARGET: {{thanos-bosh-target}}
      BOSH_CLIENT: {{thanos-bosh-username}}
      BOSH_CLIENT_SECRET: {{thanos-bosh-password}}
      BOSH_CERTIFICATES: {{thanos-bosh-certificates}}
      DIEGO_CREDENTIALS: {{thanos-cf-diego-certs}}
      ENV: thanos
      PLACEMENT_TAG: grootfs
    on_failure:
      task: publish-datadog-event
      file: grootfs-release-develop/ci/tasks/publish-datadog-event.yml
      params:
        DATADOG_API_KEY: {{datadog-api-key}}
        EVENT_NAME: vizzini-failed-standard-groot
        TAG: grootfs
  ensure:
    task: publish-datadog-event
    file: grootfs-release-develop/ci/tasks/publish-datadog-event.yml
    params:
      DATADOG_API_KEY: {{datadog-api-key}}
      EVENT_NAME: "vizzini-ending-standard-groot"
      TAG: grootfs

- name: bench-without-loops
  serial_groups:
  - deploy-thanos-cf
  public: true
  plan:
  - do:
    - aggregate:
      - get: grootfs-release-develop
        trigger: true
        passed: [deploy-thanos-cf]
        params:
          submodules: none
      - get: grootfs-bench-release
      - get: thanos-bench-time-trigger
        trigger: true
    - task: benchmark-LOCAL-LOOPLESS
      tags: [thanos]
      privileged: true
      file: grootfs-bench-release/ci/tasks/performance-tests.yml
      params:
        BOSH_TARGET: {{thanos-bosh-target}}
        BOSH_CLIENT: {{thanos-bosh-username}}
        BOSH_CLIENT_SECRET: {{thanos-bosh-password}}
        BOSH_DEPLOYMENT: cf
        BOSH_CERTIFICATES: {{thanos-bosh-certificates}}
        ERRAND_NAME: loopless-bench-errand
        DATADOG_API_KEY: {{datadog-api-key}}
        DATADOG_APPLICATION_KEY: {{datadog-application-key}}

- name: bench-with-loops
  serial_groups:
  - deploy-thanos-cf
  public: true
  plan:
  - do:
    - aggregate:
      - get: grootfs-release-develop
        trigger: true
        passed: [deploy-thanos-cf]
        params:
          submodules: none
      - get: grootfs-bench-release
      - get: thanos-bench-time-trigger
        trigger: true
    - task: benchmark-LOCAL-LOOPED
      tags: [thanos]
      privileged: true
      file: grootfs-bench-release/ci/tasks/performance-tests.yml
      params:
        BOSH_TARGET: {{thanos-bosh-target}}
        BOSH_CLIENT: {{thanos-bosh-username}}
        BOSH_CLIENT_SECRET: {{thanos-bosh-password}}
        BOSH_DEPLOYMENT: cf
        BOSH_CERTIFICATES: {{thanos-bosh-certificates}}
        ERRAND_NAME: looped-bench-errand
        DATADOG_API_KEY: {{datadog-api-key}}
        DATADOG_APPLICATION_KEY: {{datadog-application-key}}

resource_types:
- name: datadog-event
  type: docker-image
  source:
    repository: concourse/datadog-event-resource
- name: bosh-deployment-resource
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
